version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tp3'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=lau'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .  # Asegúrate de que haya un Dockerfile en la raíz del proyecto
    ports:
      - '8080:8080'  # Mapeo del puerto
    depends_on:
      - postgres  # La app depende de PostgreSQL
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
