# Usar una imagen base de Java
FROM openjdk:21-jdk-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el JAR de la aplicación al contenedor
# Asegúrate de que el JAR sea el nombre correcto que se genera en tu directorio target
COPY target/entregable3-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto en el que la aplicación va a correr
EXPOSE 8080

# Ejecutar el JAR de la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
